export const data = [
  { title: 'chill, lofi & synth ', subTitle: 'Nate Gentile', src: 'music/chill-nate.mp3', image: "image/music/chill-picture.jpg" },
  { title: 'Someone To Spend Time With', subTitle: 'Los Retros', src: 'music/someone.mp3', image: "image/music/retros.webp" },
  { title: "Everything Black", subTitle: 'Unlike Pluto, Mike Taylor', src: 'music/EverythingBlack.ogg', image: 'image/music/every.webp' },
  { title: "Surround Sound", subTitle: 'JID, 21 Savage, Baby Tate', src: 'music/JIDSurroundSound.ogg', image: 'image/music/surround.webp' },
  { title: "Heathens", subTitle: 'Twenty One Pilots', src: 'music/Heathens.ogg', image: "image/music/heathens.webp" },
  { title: "Another Love", subTitle: "Tom Odell", src: "music/AnotherLove.ogg", image: "image/music/another.webp" },
  { title: "Sex, Drugs, Etc.", subTitle: "Beach Weather", src: "music/Sex.ogg", image: "image/music/sex.webp" },
  { title: "Teeth", subTitle: "5 Seconds of Summer", src: "music/Teeth.ogg", image: "image/music/teeth.webp" },
  { title: "goosebumps", subTitle: 'Travis Scott', src: 'music/goosebumps.ogg', image: 'image/music/goosebumps.webp' },
  { title: "XO Tour Llif3", subTitle: 'Lil Uzi Vert', src: 'music/XoTourLife.ogg', image: 'image/music/xo.webp' },
  { title: "What They Want", subTitle: 'Russ', src: 'music/WhatTheyWant.ogg', image: 'image/music/what.webp' },
  { title: "Trouble", subTitle: "Coldplay", src: "music/Trouble.ogg", image: "image/music/coldplay.webp" },
  { title: "idfc", subTitle: 'blackbear', src: 'music/idfc.ogg', image: 'image/music/idfc.webp' },
  { title: "High Enough", subTitle: 'K.Flay', src: 'music/High.ogg', image: 'image/music/high.webp' },
  { title: "Falling", subTitle: 'Trevor Daniel', src: 'music/falling.ogg', image: 'image/music/falling.webp' },
  { title: "rockstar", subTitle: 'Post Malone, 21 Savage', src: 'music/rockstar.mp3', image: 'image/music/rockstar.webp' },
  { title: "Overwhelmed", subTitle: 'Ryan Mack', src: 'music/overwhelmed.ogg', image: 'image/music/over.webp' },
];