export const data = [
  { title: 'Someone To Spend Time With', subTitle: 'Los Retros', src: 'music/Someone.ogg', image: "image/music/retros.jpeg" },
  { title: "Everything Black", subTitle: 'Unlike Pluto, Mike Taylor', src: 'music/EverythingBlack.ogg', image: 'image/music/every.jpeg' },
  { title: "Surround Sound (feat. 21 Savage & Baby Tate) ", subTitle: 'JID, 21 Savage, Baby Tate', src: 'music/JIDSurroundSound.ogg', image: 'image/music/surround.jpeg' },
  { title: "Heathens", subTitle: 'Twenty One Pilots', src: 'music/Heathens.ogg', image: "image/music/heathens.jpeg" },
  { title: "Another Love", subTitle: "Tom Odell", src: "music/AnotherLove.ogg", image: "image/music/another.jpeg" },
  { title: "Sex, Drugs, Etc.", subTitle: "Beach Weather", src: "music/Sex.ogg", image: "image/music/sex.jpeg" },
  { title: "Teeth", subTitle: "5 Seconds of Summer", src: "music/Teeth.ogg", image: "image/music/teeth.jpeg" },
  { title: "goosebumps", subTitle: 'Travis Scott', src: 'music/goosebumps.ogg', image: 'image/music/goosebumps.jpeg' },
  { title: "XO Tour Llif3", subTitle: 'Lil Uzi Vert', src: 'music/XoTourLife.ogg', image: 'image/music/xo.jpeg' },
  { title: "What They Want", subTitle: 'Russ', src: 'music/WhatTheyWant.ogg', image: 'image/music/what.jpeg' },
  { title: "Trouble", subTitle: "Coldplay", src: "music/Trouble.ogg", image: "image/music/coldplay.jpeg" },
  { title: "idfc", subTitle: 'blackbear', src: 'music/idfc.ogg', image: 'image/music/idfc.jpeg' },
  { title: "High Enough", subTitle: 'K.Flay', src: 'music/High.ogg', image: 'image/music/high.jpeg' },
  { title: "Falling", subTitle: 'Trevor Daniel', src: 'music/falling.ogg', image: 'image/music/falling.jpeg' },
  { title: "rockstar", subTitle: 'Post Malone, 21 Savage', src: 'music/rockstar.ogg', image: 'image/music/rockstar.jpeg' },
  { title: "Overwhelmed (Ryan Mack Remix)", subTitle: 'Ryan Mack', src: 'music/overwhelmed.ogg', image: 'image/music/over.jpeg' },
];