// import { useEffect, useState } from "react";

// export default function LogicPlayer(audioRef ) {

//   return {
//     handleVolumeOff,
//     handleMouseUp,
//     handleRandom,
//     formattedTime,
//     formattedDuration,
//     volumeProgress,
//     progress,
//     totalSecondDuration,
//     totalDurationMinutes,
//     handleVolumeOff,
//     handleMouseUp,
//     handleVolume,
//     handleProgressBarClick,
//     handleMouseMove,
//     handleMouseDown,
//     togglePlayPause,
//     playPreviousTrack,
//     playNextTrack,
//     handleCheck,
//     isPlaying,
//     setIsPlaying,
//     currentTime,
//     setCurrentTime,
//     minutes,
//     setMinutes,
//     seconds,
//     setSeconds,
//     duration,
//     setDuration,
//     isDragging,
//     setIsDragging,
//     currentTrackIndex,
//     setCurrentTrackIndex,
//     volumePosition,
//     setVolumePosition,
//     isVolumeOff,
//     setVolumeOff,
//     isRandom,
//     setRandom,
//     audioRef,
//     handleClick
//   }
// }
